/position/:ident -> /positon/id/:id
datasektionen/dfunkt pull request #13
Opened 2016-11-03 10:27 UTC by LudwikJaniuk

Fixes #11 

Updated all the relevant places. New endpoint name so that bugs surface quickly in case I missed anything, or if anyone is still using the old identifier format.

2016-11-03 15:17 UTC, JSimo requested changes
The old role-identifier api endpoints shouldn't be removed as it currently being used and is quite useful to have. (It is just that an id endpoint is nice to have as we can guarantee that it will never change, not that we want to remove the old one)

2016-11-05 13:23 UTC, JSimo requested changes
Should have noticed it earlier, I thought the changes were made in the api endpoints. What needed changing to fix #11 was to add/edit api-endpoints not change the view urls, although it is probably a good change as well. I should have used an example url from the api instead. (I.e. http://localhost:5000/api/role/ordf instead of one being used for the views)

2016-11-05 14:47 UTC, LudwikJaniuk commented
No problem, då fixar jag det kanske imorgon

On Sat, Nov 5, 2016, 2:23 PM Jesper Simonsson <notifications@github.com>
wrote:

> *@JSimo* requested changes on this pull request.
>
> Should have noticed it earlier, I thought the changes were made in the api
> endpoints. What needed changing to fix #11
> <https://github.com/datasektionen/dfunkt/issues/11> was to add/edit
> api-endpoints not change the view urls, although it is probably a good
> change as well. I should have used an example url from the api instead.
> (I.e. http://localhost:5000/api/role/ordf instead of one being used for
> the views)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/datasektionen/dfunkt/pull/13#pullrequestreview-7314139>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGAbGVgIckB7sumV0zbkblkG_7Zqc493ks5q7INSgaJpZM4KoMZI>
> .
>

2016-11-06 10:21 UTC, LudwikJaniuk commented
Ookej, api.js, de blir en lite större ändring, men yes, då är jag med på vad som ska göras

2016-11-07 17:41 UTC, LudwikJaniuk commented
@JSimo Nu ska det vara klart. Nya endpoints gjorda för de api-endpoints som använde role identifier, men de gamla är kvar, och jag ändrade namn från "identifier" till "groupIdentifier" där det var en sån som användes, så man inte blandar ihop dem. De där ändringarna jag gjorde med view endpoints har jag behållit.

2016-11-10 16:41 UTC, JSimo approved these changes

2016-11-10 16:42 UTC, merged